### ISSUE TITLE
Symfony uuendamine

### ISSUE THREAD

**Issue by kerdokullamae** [kerdokullamae/test_koik_issued#1463]
**Reported by sven syld on 18 May 2016 07:24 UTC**
*Objekt*
Arhiivi rakendus

*Todo*
Uuendada praegune Symfony (2.3) viimase versiooni peale (3.1), ja kõik teised moodulid ka, mis vana Symfonyga enam ei tööta.

Vb on abi [sellest videost](https://knpuniversity.com/screencast/new-symfony-2.2/symfony3).

**Comment by kerdokullamae** [comment]
**Modified by mehis.muldma on 18 May 2016 07:25 UTC**

**Comment by kerdokullamae** [comment]
**Modified by mehis.muldma on 18 May 2016 15:24 UTC**

**Comment by kerdokullamae** [comment]
**Modified by mehis.muldma on 19 May 2016 15:17 UTC**

**Comment by kerdokullamae** [comment]
**Modified by mehis.muldma on 20 May 2016 19:42 UTC**

**Comment by kerdokullamae** [comment]
**Comment by mehis.muldma on 23 May 2016 15:16 UTC**
[3373] - Tegin eraldi branchi symfony uuenduste jaoks nagu sai räägitud. Panin importima ka, võid seni tehtu üle vaadata.

**Comment by kerdokullamae** [comment]
**Comment by mehis.muldma on 24 May 2016 11:22 UTC**
[=> [3375](3374]) - Genereerisin mudelid i18n tarbeks uuesti, parandus DataCacheBehavior klassis.

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 24 May 2016 11:47 UTC**
CR punktid:
1) https://www.tietotest.ee/Rahvusarhiiv/raju/changeset/3373/branches/symfony_upgrade_2_8/src/Brainart/UtilBundle/Classes/CommandNotifierTrait.php - siin on hard-codemine

2) https://www.tietotest.ee/Rahvusarhiiv/raju/changeset/3373/branches/symfony_upgrade_2_8/src/Brainart/XClassifierBundle/Model/map/XActTypeFieldI18nTableMap.php - datacache on kadund kuskile

3) https://www.tietotest.ee/Rahvusarhiiv/raju/changeset/3373/branches/symfony_upgrade_2_8/src/Brainart/XClassifierBundle/Model/om/BaseXAdminUnitType.php - paistab et datacache behavior ei ole korrektselt peale läinud. Peab olema:
<pre>
if (!XAdminUnitTypePeer::getCacheStore()) {     
    $this->currentLocale = 'et';     
};
</pre>

4) https://www.tietotest.ee/Rahvusarhiiv/raju/changeset/3373/branches/symfony_upgrade_2_8/src/Brainart/XClassifierBundle/Model/om/BaseXAdminUnitTypeI18nQuery.php - peab uurima miks on tekkinud purgeFromCache ja deleteFromCache

5) https://www.tietotest.ee/Rahvusarhiiv/raju/changeset/3373/branches/symfony_upgrade_2_8/src/Dira/MainBundle/Resources/config/services.yml hard-codemine... tühjaks ei saanud jätta?

**Comment by kerdokullamae** [comment]
**Comment by mehis.muldma on 24 May 2016 14:33 UTC**
[3376] - CR muudatused.

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 25 May 2016 07:27 UTC**

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 25 May 2016 07:28 UTC**
Sf2.8 peale viidud. 3.1 jaoks vaja uuemat PHP-d (vähemalt 5.5, aga parem veel 7)

**Comment by kerdokullamae** [comment]
**Modified by sven.syld on 15 Jul 2016 15:42 UTC**

**Comment by kerdokullamae** [comment]
**Comment by timo.torim on 28 Jul 2016 13:42 UTC**
[3384] - mergesin symfony 2.8 trunki

**Comment by kerdokullamae** [comment]
**Comment by timo.torim on 28 Jul 2016 13:47 UTC**
igaksjuhuks juurde, et oma keskkonnda config'us tuleb välja võtta 
    debug.twig.extension:
        class: Twig_Extensions_Extension_Debug
        tags: [name: 'twig.extension' }]({)
Kui caches olevatele failidele ei saa ligi, siis tuleks enda app_'keskkond'.php's teha samad muudatused nagu näiteks app_timo.php's.

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 1 Aug 2016 12:33 UTC**
Paistab, et selle mergega on kõik viimased muudatused minema pühitud. Ja branchi võib ka maha võtta, seda pole enam vaja.

**Comment by kerdokullamae** [comment]
**Comment by timo.torim on 1 Aug 2016 13:52 UTC**
[3385] - puuduvad muudatused tagasi

**Comment by kerdokullamae** [comment]
**Comment by sven.syld on 21 Sep 2016 14:44 UTC**
Sain uues webis pildi ette, aga indeksi populeerimine annab vea:
```
vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:158 - annab vea "index_not_found_exception", kuigi ta peaks selle populeerimisel ise looma
```

Ilmselt ilma Sf ja ES'ide-asjade uuendamiseta edasi ei pääse.

Töötav konf (config_$ENV.yml):
```
dira_elastica.client.host: dev-ais-idx1.arhiiv.ee
dira_main.service.schemas_host: http://sven.dev-ais-web.arhiiv.ee:10080
dira_main.sitemap.host: 'sven.dev-ais-web.arhiiv.ee:10080'
sub_app.session.cookie_domain: .sven.dev-ais-web.arhiiv.ee
sub_app.urls:
    DIRA: http://sven.dev-ais-web.arhiiv.ee
    OPENDATA: http://opendata.sven.dev-ais-web.arhiiv.ee
    CROWDSOURCING: http://crowdsourcing.sven.dev-ais-web.arhiiv.ee
sub_app.routing_host.DIRA: sven.dev-ais-web.arhiiv.ee
sub_app.routing_host.OPENDATA: opendata.sven.dev-ais-web.arhiiv.ee
sub_app.routing_host.CROWDSOURCING: crowdsourcing.sven.dev-ais-web.arhiiv.ee

propel:
    dbal:
        ...oma user-pass
        dsn:                        pgsql:host=dev-ais-db.arhiiv.ee;dbname=sven_dira
```

web alla tuleb teha .htaccess (näide sealsamas), lisada:
```
RewriteCond %{SERVER_PORT} 10080
```

Uues arenduses on composer süsteemi installitud, st:
```
$ php composer.phar
```
asemel
```
$ composer
```
